<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/runtime:9.0</ContainerBaseImage>
    <ContainerRepository>mungert/networkmonitorprocessor</ContainerRepository>
    <ContainerImageTag>1.5.1</ContainerImageTag>
    <StartupObject>NetworkMonitor.Processor.Program</StartupObject>
      <IsPublishable>true</IsPublishable>
  <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
   <ContainerEntrypoint>/app/entrypoint.sh</ContainerEntrypoint>
   <ContainerUser>root</ContainerUser>
 <ContainerInitializationCommand>chmod +x /app/entrypoint.sh</ContainerInitializationCommand>
 
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
  </ItemGroup>
    <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetworkMonitorLib\NetworkMonitor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="openssl\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>openssl\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>

  <ItemGroup>
  <Content Include="entrypoint.sh">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <TargetPath>entrypoint.sh</TargetPath>
  </Content>
</ItemGroup>

</Project>
